In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
print("Hello World")

Hello World


In [35]:
a = 5
b = 4
if (a>b) :
    print(a , "is Greater")

5 is Greater


In [36]:
arr = np.array([1,3,5,6,2,61,6])
print(arr)

[ 1  3  5  6  2 61  6]


In [37]:
print(np.__version__)

1.22.4


In [38]:
print(type(arr))

<class 'numpy.ndarray'>


In [39]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr2d)z

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
## This arr.ndim Checks the Order of the multi-dimensional array 
a = np.array(5)
b = np.array([1,2])
c = np.array([[1,2],[3,4]])
# d = np.array([[[1,2,3],[3,4,4]],
#                [5,6,7]])
print(a.ndim)
print(b.ndim)
print(c.ndim)


0
1
2


In [41]:
## When an array is created you can define the number of Dimensions using arr.ndmin
import numpy as np 

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print(type(arr))
print(arr.ndim)


[[[[[1 2 3 4]]]]]
<class 'numpy.ndarray'>
5
